field.storage_settings.entity_reference_override:
  type: base_entity_reference_field_settings
  label: 'Field storage settings'

field.field_settings.entity_reference_override:
  type: field.field_settings.entity_reference
  label: 'Field config settings'
  mapping:
    overwritable_properties:
      type: sequence
      label: 'Properties to overwrite'
      sequence:
        type: mapping
        label: 'Bundle'
        mapping:
          options:
            type: sequence
            label: 'Properties to overwrite'
            sequence:
              type: string
              label: 'Field'

field.widget.settings.entity_reference_override_autocomplete:
  type: field.widget.settings.entity_reference_autocomplete
  label: 'Entity reference autocomplete display format settings'
